version: "3.8"

services:
  # app:
  #   build:
  #     dockerfile: ./Dockerfile
  #     context: ./
  #   command: npm run dev:backend
  #   restart: on-failure
  #   volumes:
  #     - ${APP_DATA_DIR}/data/app:/data
  #   environment:
  #     PORT: "3006"
  #     VUE_APP_API_URL:
  #     BACKUP_STATUS_FILE: /data/backup-status.json
  #     LND_REST_HIDDEN_SERVICE: rest.onion
  #     LND_GRPC_HIDDEN_SERVICE: grpc.onion
  #     LIGHTNING_NETWORK: "regtest"
  #     LIGHTNING_PORT: 8001
  #     JSON_STORE_FILE: /data/state.json
  #     TOR_PROXY_IP: tor
  #     TOR_PROXY_PORT: 9050
  #   ports:
  #     - "3006:3006"

  rtl:
    image: shahanafarooqui/rtl:0.12.3
    restart: on-failure
    ports:
      - 1235:3000
    environment:
      APP_PASSWORD: moneyprintergobrrr
      LN_IMPLEMENTATION: CLT
      LN_SERVER_URL: http://lightning-rest:3001/v1
      MACAROON_PATH: /c-lightning-rest/certs
      RTL_CONFIG_PATH: /data/
      RTL_COOKIE_PATH: /data/.cookie
    volumes:
      - "${APP_DATA_DIR}/data/rtl:/data"
      - "${APP_DATA_DIR}/data/c-lightning-rest/certs:/c-lightning-rest/certs"
  
  lightning-rest:
    image: saubyk/c-lightning-rest:0.7.2
    restart: on-failure
    ports:
      - 1234:3001
    environment:
      PROTOCOL: "http"
    volumes:
      - "${APP_DATA_DIR}/data/c-lightning-rest/certs:/usr/src/app/certs"
      - "${APP_DATA_DIR}/data/lightning/lightning:/root/.lightning"

  lightning:
    image: elementsproject/lightningd:v0.11.1
    restart: on-failure
    command:
      - --bitcoin-rpcconnect=${APP_BITCOIN_NODE_IP}
      - --bitcoin-rpcuser=${APP_BITCOIN_RPC_USER}
      - --bitcoin-rpcpassword=${APP_BITCOIN_RPC_PASS}
      - --log-level=debug
    volumes:
      - "${APP_DATA_DIR}/data/lightning/lightning:/root/.lightning"