version: "3.8"

services:
  # app:
  #   build:
  #     dockerfile: ./Dockerfile
  #     context: ./
  #   command: npm run dev:backend
  #   restart: on-failure
  #   volumes:
  #     - ${APP_DATA_DIR}/data/app:/data
  #   environment:
  #     PORT: "${APP_CORE_LIGHTNING_IP}"
  #     VUE_APP_API_URL:
  #     BACKUP_STATUS_FILE: /data/backup-status.json
  #     LND_REST_HIDDEN_SERVICE: rest.onion
  #     LND_GRPC_HIDDEN_SERVICE: grpc.onion
  #     LIGHTNING_NETWORK: "regtest"
  #     LIGHTNING_PORT: 8001
  #     JSON_STORE_FILE: /data/state.json
  #     TOR_PROXY_IP: tor
  #     TOR_PROXY_PORT: 9050
  #   ports:
  #     - "${APP_CORE_LIGHTNING_IP}:${APP_CORE_LIGHTNING_IP}"
      # networks:
      #   default:
      #     ipv4_address: ${APP_CORE_LIGHTNING_IP}


  rtl:
    image: shahanafarooqui/rtl:0.12.3
    restart: on-failure
    ports:
      - 1235:3000
    environment:
      APP_PASSWORD: moneyprintergomoo
      LN_IMPLEMENTATION: CLT
      LN_SERVER_URL: http://${APP_CORE_LIGHTNING_REST_IP}:${APP_CORE_LIGHTNING_REST_PORT}/v1
      MACAROON_PATH: /c-lightning-rest/certs
      RTL_CONFIG_PATH: /data/
      RTL_COOKIE_PATH: /data/.cookie
    volumes:
      - "${APP_DATA_DIR}/data/rtl:/data"
      - "${APP_CORE_LIGHTNING_REST_CERT_DIR}:/c-lightning-rest/certs"
  
  c-lightning-rest:
    image: saubyk/c-lightning-rest:0.7.2
    restart: on-failure
    ports:
      - ${APP_CORE_LIGHTNING_REST_PORT}:${APP_CORE_LIGHTNING_REST_PORT}
    environment:
      PORT: "${APP_CORE_LIGHTNING_REST_PORT}"
      PROTOCOL: "http"
    volumes:
      - "${APP_CORE_LIGHTNING_REST_CERT_DIR}:/usr/src/app/certs"
      - "${APP_DATA_DIR}/data/lightningd:/root/.lightning"
    networks:
      default:
        ipv4_address: ${APP_CORE_LIGHTNING_REST_IP}

  lightningd:
    image: elementsproject/lightningd:v0.11.1
    restart: on-failure
    ports:
      - ${APP_CORE_LIGHTNING_DAEMON_PORT}:9735
    command:
      - --bitcoin-rpcconnect=${APP_BITCOIN_NODE_IP}
      - --bitcoin-rpcuser=${APP_BITCOIN_RPC_USER}
      - --bitcoin-rpcpassword=${APP_BITCOIN_RPC_PASS}
      - --proxy=${TOR_PROXY_IP}:${TOR_PROXY_PORT}
      - --bind-addr=${APP_CORE_LIGHTNING_DAEMON_IP}:9735
      - --addr=statictor:${TOR_PROXY_IP}:29051
      - --tor-service-password=${TOR_PASSWORD}
    volumes:
      - "${APP_DATA_DIR}/data/lightningd:/root/.lightning"
    networks:
      default:
        ipv4_address: ${APP_CORE_LIGHTNING_DAEMON_IP}